version: "3"
services:
  webserver:
    build:
    # where to find a Dockerfile to build from
      context: webserver/.
    volumes:
      - ../.:/usr/local/apache2/htdocs/.
       # use host's shared memory when running chrome
      - /dev/shm:/dev/shm
      - ~/.ssh:/home/user/.ssh
    env_file:
      - ~/.docker/.env
    environment:
      - VIRTUAL_HOST=users.local
      # The following 3 lines were added to use HTTPS - but seems it doesn't work
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
      - CERT_NAME=YOUR_CERT_NAME ## Add this
    ports:
      # Use for debugging, access to vnc to show running test
       - "9099:80"
       - "5902:5900"
    container_name: users_webserver
    networks:
      - default_local
    # Allow to run chrome
    cap_add:
      - SYS_ADMIN
networks:
  default_local:
    external: true
